# Generated by Django 4.1.7 on 2023-04-10 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_custom_is_active_alter_custom_photo_onlineuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='bio',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='custom',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/images', verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='custom',
            name='friends',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='custom',
            name='job_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Friends_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
