# Generated by Django 4.1.7 on 2023-03-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_custom_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/images', verbose_name='photo'),
        ),
    ]
