# Generated by Django 4.1.7 on 2023-04-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='certificaty_URL',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
