# Generated by Django 4.1.7 on 2023-04-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_certificaty_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='certificaty_URL',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
