# Generated by Django 3.2.12 on 2023-04-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Qualification',
            field=models.TextField(default=2, verbose_name='Qualification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='Responsibilities',
            field=models.TextField(default=2, verbose_name='Responsibilities'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=8),
            preserve_default=False,
        ),
    ]
