# Generated by Django 3.2.12 on 2023-04-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20230405_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='position',
            field=models.CharField(choices=[('S', 'Senior'), ('J', 'Junior'), ('I', 'Intermediate'), ('P', 'Professional'), ('f', 'Fresh Graduate')], default='f', max_length=1),
        ),
    ]
