# Generated by Django 3.2.12 on 2023-04-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(default=2, max_length=20, verbose_name='city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(default=2, max_length=20, verbose_name='country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='full_address',
            field=models.TextField(default=2, max_length=255, verbose_name='full_address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='postcode',
            field=models.IntegerField(default=2, max_length=10, verbose_name='postcode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='region',
            field=models.CharField(default=2, max_length=20, verbose_name='region'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='Qualification',
            field=models.TextField(null=True, verbose_name='Qualification'),
        ),
        migrations.AlterField(
            model_name='job',
            name='Responsibilities',
            field=models.TextField(null=True, verbose_name='Responsibilities'),
        ),
        migrations.AlterField(
            model_name='job',
            name='position',
            field=models.CharField(choices=[('Senior', 'Senior'), ('Junior', 'Junior'), ('Intermediate', 'Intermediate'), ('Professional', 'Professional'), ('Fresh Graduate', 'Fresh Graduate')], max_length=100),
        ),
    ]
