# Generated by Django 3.2.12 on 2023-04-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20230407_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(max_length=20, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='job',
            name='country',
            field=models.CharField(max_length=20, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='job',
            name='full_address',
            field=models.TextField(max_length=255, null=True, verbose_name='full_address'),
        ),
        migrations.AlterField(
            model_name='job',
            name='postcode',
            field=models.IntegerField(max_length=10, null=True, verbose_name='postcode'),
        ),
        migrations.AlterField(
            model_name='job',
            name='region',
            field=models.CharField(max_length=20, null=True, verbose_name='region'),
        ),
    ]
