# Generated by Django 4.1.7 on 2023-04-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_job_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='position',
            field=models.CharField(choices=[('Senior', 'Senior'), ('Junior', 'Junior'), ('Intermediate', 'Intermediate'), ('Professional', 'Professional'), ('FreshGraduate', 'Fresh Graduate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
