# Generated by Django 4.1.7 on 2023-04-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_community_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='community',
            field=models.CharField(max_length=255),
        ),
    ]
