# Generated by Django 4.1.7 on 2023-04-06 05:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ads_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=None),
        ),
    ]
