# Generated by Django 4.1.7 on 2023-04-06 05:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ads_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
    ]
