# Generated by Django 4.1.7 on 2023-03-27 19:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_remove_problem_content_problem_community_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], null=True, size=None),
        ),
    ]
