# Generated by Django 4.1.7 on 2023-03-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_problem_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
