# Generated by Django 4.1.7 on 2023-03-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_solution_created_at_solution_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='community',
            field=models.CharField(default='programming', max_length=255),
            preserve_default=False,
        ),
    ]
