# Generated by Django 4.1.7 on 2023-03-29 19:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0008_solution_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='likes',
            field=models.ManyToManyField(related_name='liked_solution', to=settings.AUTH_USER_MODEL),
        ),
    ]
