# Generated by Django 3.2.18 on 2023-04-01 05:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0009_solution_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='likes',
            field=models.ManyToManyField(related_name='likes_solution', to=settings.AUTH_USER_MODEL),
        ),
    ]
