# Generated by Django 4.1.7 on 2023-04-02 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0009_solution_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='likes',
            field=models.ManyToManyField(related_name='likes_solution', to=settings.AUTH_USER_MODEL),
        ),
    ]
