# Generated by Django 4.1.7 on 2023-04-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_problem_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
